services:
  data-collection-service:
    build: ./
    env_file: .env
    environment:
      KAFKA_BROKERS: kafka:19092 # Internal docker communication
      KAFKA_CLIENT_ID: data-collector
      KAFKA_GROUP_ID: data-collector-group
      KAFKA_TOPIC_DEFAULT: data-collection
    networks:
      - network_shared
    volumes:
      - ./logs:/app/logs

networks:
  network_shared:
    # docker network create network_shared
    external: true # Ensure this network exists or create it manually
