services:
  data-collection-service:
    build: .
    env_file: .env
    environment:
      - MYSQL_HOST=mysql
      - MONGO_URI=mongodb://mongo_user:mongo_password@mongo:27017/admin
      - KAFKA_BROKER=kafka:9092
    networks:
      - network_shared

networks:
  network_shared:
    # docker network create network_shared
    external: true # Ensure this network exists or create it manually
