services:
  data-collection-service:
    build:
      context: ../..
      dockerfile: .docker/production/Dockerfile
    env_file:
      - .env.${APP_ENV}
    environment:
      APP_ENV: production
      KAFKA_BROKERS: kafka:19092 # Internal docker communication
    networks:
      - network_shared
    volumes:
      - ./logs:/app/logs

networks:
  network_shared:
    # docker network create network_shared
    external: true # Ensure this network exists or create it manually
