services:

  data-collection-service:
    build:
      context: ../../
      dockerfile: .docker/production/Dockerfile
    env_file:
      - .env.${APP_ENV}
    networks:
      - network_shared
    volumes:
      - logs:/workspaces/app/logs
    restart: always
    command: "npm start"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          # memory: 2048M          
          # reservations:
          #   cpus: "0.1"          
          #   memory: 256M          
      restart_policy:
        condition: on-failure
    # expose:
    #   - "3000" # only internal
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3


volumes:
  logs:


networks:
  network_shared:
    # docker network create network_shared
    external: true # Ensure this network exists or create it manually
